baseURL: https://rbhadti94.github.io/
languageCode: en-us
title: Personal Bio

languages:
  en:
    languageName: English
    weight: 1

# Enable global emoji support
enableEmoji: true

params:
  # GitHub repo URL of your site
  gitRepo: https://github.com/hugo-toha/hugo-toha.github.io
  enableBlogPost: false